services:
  frontend:
    build:
      context: ./frontend
      target: dev
    command: pnpm run dev
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./frontend/package.json

  backend:
    build:
      context: ./backend
      target: dev
    command: npm run dev
    ports:
      - 8000:8000
      - 9229:9229
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - dist
            - node_modules
        - action: rebuild
          path: ./backend/package.json
